name: 'Godot Export'
description: 'Automatically exports your Godot games.'
author: 'Firebelley'
branding:
  icon: 'box'
  color: 'white'
inputs:
  # required inputs
  godot_executable_download_url:
    description: The download url of the 64 bit Linux Headless Godot executable.
    required: true
  godot_export_templates_download_url:
    description: The url of the export templates corresponding to the Godot executable version.
    required: true
  relative_project_path:
    description: The relative path containing the "project.godot" file.
    required: true

  # optional inputs
  archive_export_output:
    description: If exported binaries should be archived. Note that when create_release is true builds attached to the release may archived regardless of this setting.
    default: false
    required: false
  archive_single_release_output:
    description: If create_release is true, should the export output be archived if it is contained in a single file. Useful for exports with the "Embed PCK" option enabled.
    default: true
    required: false
  base_version:
    description: Base version. Patch versions are incremented when this action runs.
    default: 0.0.1
    required: false
  create_release:
    description: If a release should be created.
    default: true
    required: false
  generate_release_notes:
    description: If release notes should be automatically generated.
    default: false
    required: false
  relative_export_path:
    description: If provided, binaries will be exported to this directory. This should be a path relative to the root of your Git repository.
    default: ''
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
